### ISSUE TITLE
Can't install in node:14-alpine

### ISSUE THREAD

**Issue by suruaku** [mikeu/vue2-leaflet-fullscreen#1]
Even when I install git and openssh, installation hang and repository is not responding
 ```
RUN apk update \
  && apk add git openssh
```

```
 => => # npm ERR! code 128
 => => # npm ERR! Command failed: git clone --mirror -q https://github.com/Leaflet/Leaflet.fullscreen.git /root/.npm/_cacache/
 => => # tmp/git-clone-d8a68c2f/.git
 => => # npm ERR! warning: templates not found in /tmp/pacote-git-template-tmp/git-clone-982a1a5f
 => => # npm ERR! fatal: the remote end hung up unexpectedly
 => => # npm ERR!
```

maybe someone had similar proble?

**Comment by mikeu** [comment]
Hi @suruaku , have you had any luck resolving this issue?

If not then I'm happy to try to help, but could use some more context. Why does installing the git and openssh APKs have anything to do with this project? I'm unclear why running those commands would have anything to do with [Leaflet/Leaflet.fullscreen](https://github.com/Leaflet/Leaflet.fullscreen) either, and regardless, that is a separate, independent repo from this one, and also not an Android application.

**Comment by suruaku** [comment]
Sorry, I totally forgot to mention that I'm trying to install this in Docker using node:14-alpine image. I can successfully install the project with `npm install` but using `npm ci` fails in docker, but works on my computer. 

Alpine image doesn't have git so `apk add git` will install git package for Alpine, nothing Android related. For `npm install` openssh is not needed, only git.

I have no idea why it's like that, never had similar issues. I think for now I'll use npm install or fork the project. Maybe this will fix itself at some point.

**Comment by mikeu** [comment]
You know what, I honestly cannot remember why the package.json here referenced the Leaflet.fullscreen git repo directly instead of the npm package. I switched it to use the package, without any apparent change to the behaviour, so I just cut a new patch release.

Still doesn't explain why cloning the repo was failing for you, but please test out v1.0.1 and let me know if that at least clears things up!

**Comment by suruaku** [comment]
sweet, `npm ci` works now! thanks a lot

**Comment by mikeu** [comment]
No prob, thanks for bringing it to my attention :)
